### PR TITLE
Support daemonizing of delayed_job_celluloid

### PR DESCRIPTION
**Pull request by wtfiwtz**
This is an amazing find for me! We have been struggling with DJ memory usage for months, trying everything, including stripping out Rails components in the DJ load sequence. We hope to get this working with 10 threads, so our memory usage will be a lot less than 2Gb, so we can replace our existing background job script!

Unfortunately, I could not get Minitest to work with the existing tests... even after switching to `Klass < Minitest::Test`. Which version of minitest are you using? Might have to leave this for another day.

Cheers,
Nigel

### CODE REVIEW

**Comment by steelheaddigital** [comment]
Hey there, thanks for contributing, I'm glad you're finding this useful!  I actually haven't looked at or used this in quite a while.  I'm using Minitest 4.7.5.  I updated all the dependencies and ran the tests with that version.  They run, but of course there are errors with the updates.  I'll try to look more this weekend and hopefully we can get you going.

**Comment by steelheaddigital** [comment]
I went ahead and merged your pull request.  I made a few changes so that logging would work right and so it would throw an exception if Daemons isn't loaded.  Additionally, I added an argument so "-m" so that the Daemons monitor process can be started.  

Other changes include moving each test file into it's own rake task.  They really need to be run one at at time since the threads the start interfere with each other.  I also added a test Rails app to just do some basic smoke testing.  Let me know how everything goes for you and thanks for contributing.  

I would be curious to know what kind of performance improvements you see from using this, so let me know if you get a chance.  Thanks!

**Comment by wtfiwtz** [comment]
Thanks @steelheaddigital... I'm investigating a race condition - not all threads start, e.g. -n 6 only starts 3 or 4 threads - seems to be only in daemonization mode though... possibly because I am using some logging globals across DJ workers, preventing the manager from finishing its spawning loop... but otherwise we are on the verge of testing this in production with real life data so I'll let you know! The initial results look really good though... dramatically lower memory overall.

**Comment by steelheaddigital** [comment]
Interesting @wtfiwtz .  Try out the latest code I checked in.  Most of the changes I made to your pull request had to do with logging and dealing with file handles in the daemon process.  I added some code to reopen file handles when the daemon process is forked.  This should open the file handles in the daemon process and close and flush the previous IO in the parent process.  Perhaps the race condition is caused by not closing the file handles in the parent process when the daemon process is forked.  If so, the code I added should fix that.  In my tests, it seemed to be starting all the workers fine and they all processed jobs.  I didn't stress test real heavily, but the changes might solve your problem.

**Comment by wtfiwtz** [comment]
Okay after about 5 hours of looking at Celluloid's message passing between actors, I've found something:

``` ruby
      @ready.each_with_index do |worker, index|
        worker.name = "delayed_job.#{index}"
        worker.async.start
      end
```

If I make both worker calls 'async', then all requested threads start. However, if I make both worker calls 'sync', then only a single thread will start, and the Manager stalls waiting for some response from worker 1.

Still not sure exactly why but there is something going on in the internals of Celluloid with respect to the `DelayedJobCelluloid::Manager` when `name` is sync and `start` is async. I have a `sleep(20)` directly after this loop, so it looks like Celluloid is either trying to suspend or resume a task prior to this - probably trying to finish all the outstanding work in the manager's queue before it goes to sleep. However, something in the timers has fired, and consequently, the manager get deadlocked while waiting for an acknowledgement in the `deliver` call. As a result, it doesn't finish delivering the worker `start` message asynchronously to the remaining workers.

Here's the stack trace for the manager 20 seconds later (captured with `Celluloid.stack_dump`):

```
/Users/wtfiwtz/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/thread.rb:72:in `sleep'
/Users/wtfiwtz/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/thread.rb:72:in `block (2 levels) in wait'
/Users/wtfiwtz/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/thread.rb:68:in `handle_interrupt'
/Users/wtfiwtz/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/thread.rb:68:in `block in wait'
/Users/wtfiwtz/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
/Users/wtfiwtz/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/thread.rb:66:in `wait'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:40:in `block in deliver'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:38:in `synchronize'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:38:in `deliver'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:100:in `resume'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/actor.rb:264:in `block in before_suspend'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/timer.rb:97:in `call'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/timer.rb:97:in `fire'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/events.rb:43:in `fire'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/events.rb:85:in `block in fire'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/events.rb:84:in `reverse_each'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/events.rb:84:in `fire'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/group.rb:80:in `fire'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/timers-4.0.1/lib/timers/group.rb:64:in `wait'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/Users/wtfiwtz/.rvm/gems/ruby-2.0.0-p481/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

Not sure if this is a problem only for us (as we have hacked Delayed_Job a little bit as well for our own needs) but if you ever see any threads not start, this might be the cause.

I'll make this change locally and see if this resolves our problem in the longer term. I'll also dig into the event firing a bit more to see if I can figure out what message the Manager is responding to.

**Comment by wtfiwtz** [comment]
Actually that backtrace looks pretty normal. The 'fire' event is the end of the timer, and it passes a `deliver` message to the task, probably with a 'nil' value, and now its just waiting on the task to respond. 

I guess the main question is why the Manager never sends out all async requests to begin with (in order to start the workers) so I'll keep looking there.

**Comment by wtfiwtz** [comment]
Okay I think I have it this time... we are not protecting the `@ready` list properly for multi-threaded access. When workers 1, 2, 3... etc start they will delete themselves from the `@ready` list in the Manager, by sending back an async `work` request. I'll see if I can fix this up, so that it doesn't mess with the loop where the (later-stage) workers are being started.

I thought I looked into this before the other day, but perhaps I forgot to clone the list properly (rather than just duplicate the reference to the list).

**Comment by wtfiwtz** [comment]
The issue was definitely with the `@ready` list, but we probably need to put in a proper mutex on both `@ready` and `@busy`. I should be able to send you a PR tomorrow.

I've been running it in a production-ready mode on our application, and the memory usage saved is pretty astounding. A celluloid process with 5 multi-threaded workers, processing a normal workload, takes only 180-190Mb of non-shared memory. We typically run GC at the end of each DJ job. The same with our normal DJ workers would probably be around 1.3Gb in total. That's a saving of about 85% with fairly equivalent (if not better) performance! A typical DJ worker is 240-250Mb + a 'master' process which takes another 130Mb.

Its not entirely resilient - synchronizing three particularly heavy users was enough for the celluloid process to crash out and self-restart a few times - consuming in excess of 2Gb memory (non-shared). But at the moment, we actually run our heaviest users under a separate synchronizing process, so we will probably leave this running under the old multi-threaded script for now. 

The results are very promising - I hope to have this running in production 100% tomorrow, fingers crossed.

**Comment by wtfiwtz** [comment]
Hi @steelheaddigital, we have this in production for 24 hours now, and its very stable.

I had to use Ruby 1.9.3, not Ruby 2.0 as the memory usage profile is quite different and we hit server limits much quicker on Ruby 2.0 (... the celluloid process kept restarting every 5-10 minutes).

With 6 threads, its stabilised around 655mb on server #1:

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND  
23791 soupmail  30  10 1336m 655m 5268 S 20.5 17.5 276:04.06 ruby               

Very happy with the outcome, so thank you! Don't let me forget to finish the pull request to eliminate the race condition though.

Cheers, Nigel

**Comment by steelheaddigital** [comment]
That's great @wtfiwtz, I'm glad it's working out for you!  Thanks for getting me the stats.  Definitely submit that pull request when you get a chance, and thanks for your work on this.

-Tom

**Pull request closed without merging**
